import {editorialOutreachAdapter} from '../../runtime/adapters.js';
import test from 'node:test';import assert from 'node:assert/strict';import {openRouteScout,commercialEvidenceBranch,prepareRouteAssets} from '../../runtime/open-route-scout.js';import directory from '../../state/open-route-directory.json' with {type:'json'};
const formation={id:'sierra-gorda-fourth-grinding-line',theme:'Sierra Gorda has begun a US$725 million brownfield copper expansion',status:'FORMING',new_to_radar:true,location:'Antofagasta Region, Chile',why_surfaced:'Physical execution added to an approved project.',causal_chain:{industries:['Copper mining','Molybdenum','Grinding equipment','Mine construction','Grid and electrification materials']},evidence:[{fact:'KGHM says construction of the fourth grinding line has started and values the project at about US$725 million.',url:'https://media.kghm.com/example'}],contradictions:['Expected output is forecast rather than realised.'],missing_evidence:['Detailed construction schedule']};
test('Sierra Gorda discovers multiple verified formation-specific routes',()=>{const r=openRouteScout({formation,directory});assert.ok(r.candidates.length>=4);assert.ok(r.candidates.some(x=>x.destination_id==='MINING-WEEKLY-TIP'));assert.ok(r.candidates.every(x=>x.evidence_source_url));});
test('energy logistics retains the verified global financial GuestViews route',()=>{
  const energy={...formation,id:'global-energy-logistics-refining-bottleneck',status:'CONFIRMED',causal_chain:{industries:['Oil shipping','Refining','Diesel and jet fuel','Storage and strategic reserves']}};
  const r=openRouteScout({formation:energy,directory});
  assert.ok(r.candidates.some(d=>d.destination_id==='REUTERS-BREAKINGVIEWS-GUEST'));
  assert.ok(!r.candidates.some(d=>d.destination_id==='MINING-WEEKLY-TIP'));
});
test('assets differ by destination class and require editorial transformation',()=>{const r=openRouteScout({formation,directory});const a=prepareRouteAssets({formation,candidates:r.candidates});assert.ok(new Set(a.map(x=>x.format)).size>1);assert.ok(a.every(x=>x.state==='INTERNAL_BRIEF_REQUIRES_EDITORIAL_TRANSFORMATION'));});
test('commercial hypotheses remain hypotheses and preserve formation state',()=>{const c=commercialEvidenceBranch(formation);assert.equal(c.does_not_modify_formation_state,true);assert.ok(c.hypotheses.every(h=>h.result==='UNKNOWN'&&h.unknowns.includes('willingness_to_pay')));});

test('route scoring includes novelty and contribution value',()=>{const r=openRouteScout({formation,directory});assert.ok(r.candidates.every(x=>typeof x.score_factors.novelty==='number'));assert.ok(r.candidates.every(x=>typeof x.score_factors.contribution_value==='number'));});
test('commercial branch is formation-generic and keeps payment evidence unknown',()=>{const c=commercialEvidenceBranch({...formation,causal_chain:{industries:['Semiconductors']}});assert.ok(c.hypotheses.every(h=>h.unknowns.includes('willingness_to_pay')));assert.ok(c.hypotheses.every(h=>!h.buyer_class.startsWith('Mining ')));});

test('route assets carry audience-specific intent, angle and intelligence visual brief',()=>{const r=openRouteScout({formation,directory});const a=prepareRouteAssets({formation,candidates:r.candidates});assert.ok(a.every(x=>x.intended_action&&x.angle&&x.visual_brief?.type==='causal_formation_card'));assert.ok(new Set(a.map(x=>x.lane)).size>=3);});

test('discovery retains account-required routes without making them executable',()=>{const r=openRouteScout({formation,directory});for(const id of ['KITCO-CONTRIBUTOR','HOTCOPPER-CONTRIBUTOR','INVESTING-COM-AU-CONTRIBUTOR','EMRADAR-X-OROKNOWS']){assert.ok(r.discovered.some(d=>d.destination_id===id&&d.classification==='DISCOVERY_ONLY'));assert.ok(!r.candidates.some(d=>d.destination_id===id));}});
test('only current authorization permits the existing X route into preparation',()=>{const r=openRouteScout({formation,directory,authorizedAccounts:['EMRADAR-X-OROKNOWS']});assert.ok(r.candidates.some(d=>d.destination_id==='EMRADAR-X-OROKNOWS'));assert.ok(!r.candidates.some(d=>d.destination_id==='KITCO-CONTRIBUTOR'));});
test('route scoring preserves observed zero feedback separately from unknown',()=>{const r=openRouteScout({formation,directory,learning:{'MINING-WEEKLY-TIP':{score:0}}});assert.equal(r.candidates.find(d=>d.destination_id==='MINING-WEEKLY-TIP').score_factors.historical_route_performance,0);assert.equal(r.candidates.find(d=>d.destination_id==='REDIMIN-EDITORIAL').score_factors.historical_route_performance,'UNKNOWN');});
test('route preparation preserves geography, radar novelty and unknown audience novelty',()=>{const r=openRouteScout({formation,directory});const a=prepareRouteAssets({formation,candidates:r.candidates});assert.ok(a.every(d=>d.location===formation.location&&d.new_to_radar===true&&d.what_they_do_not_already_know.startsWith('UNKNOWN')));assert.equal(formation.status,'FORMING');});
test('unverified contact records remain rejected',()=>{const r=openRouteScout({formation,directory:{destinations:[{...directory.destinations[1],verification_state:'UNKNOWN',evidence_source_url:null}]}});assert.equal(r.candidates.length,0);assert.equal(r.discovered[0].classification,'NO_VERIFIED_ROUTE');});
test('scout does not fabricate external copy or an editorial approval',()=>{const r=openRouteScout({formation,directory});const assets=prepareRouteAssets({formation,candidates:r.candidates});for(const a of assets){assert.equal(a.source_state,'FORMING');assert.equal(a.editorial_system,undefined);assert.equal(a.copy,null);}});

const {fixture,editorialBudget,editorialHarness}=await import('./fixture.js');
const {GraphEngine}=await import('../../runtime/graph.js');
async function sourceGraph({configured=false,cost='UNKNOWN'}={}){const f=await fixture();f.p.product_identity='EMRADAR';f.p.budget=editorialBudget;f.p.signals[0]={id:formation.id,revision:'r1',state:formation.status,evidence:['E1'],source_title:formation.theme,location:formation.location,new_to_radar:true,source_facts:[{id:'E1',text:formation.evidence[0].fact,url:formation.evidence[0].url}],source_uncertainty:formation.contradictions,causal_chain:formation.causal_chain};f.p.destinations=configured?[{...f.p.destinations[0],signal_ids:[formation.id]}]:[];const engine=new GraphEngine({store:f.store,products:{EMRADAR:f.p},harness:editorialHarness(),adapters:{OPEN_ROUTE:editorialOutreachAdapter({routeSupported:()=>false,senderIdentity:()=>({name:'Sean Walker',address:'oroknows@gmail.com',approved:true}),sendEmail:async()=>{throw new Error('UNEXPECTED_EXTERNAL_ACTION');}}),LOCAL:f.adapter,X:{formats:['text'],cost,authorized:async()=>false,publish:async()=>{throw new Error('UNEXPECTED_EXTERNAL_ACTION');}}}});return {...f,engine,input:{product:'EMRADAR',campaign_id:'SAFE_OPEN_ROUTE_REVIEW',signal_id:formation.id}};}
test('actual graph discovers alongside configured routes and preserves source truth',async()=>{const f=await sourceGraph({configured:true});const before=structuredClone(f.p);const r=await f.engine.run(f.input);assert.ok(r.route_plan.candidates.length>1);assert.ok(r.selection.options.some(o=>o.id==='local-a'));assert.deepEqual(f.p,before);assert.equal(r.status,'AWAITING_REVIEW');assert.ok(r.nodes.some(n=>n.node==='commercial_evidence'));assert.ok(!r.nodes.some(n=>n.node==='execute'));});
test('open-route review stops execution and keeps unknown declared cost unknown',async()=>{const f=await sourceGraph();const r=await f.engine.run(f.input);assert.equal(r.status,'AWAITING_REVIEW');const proposal=await f.store.get('publication_review:'+r.review.proposal_id);assert.equal(proposal.cost_state,'ZERO');await f.engine.approvePublication(r.review);const [approved]=await f.engine.distributeApproved();assert.equal(approved.receipt.error,'TRANSPORT_UNAVAILABLE');assert.notEqual(approved.receipt.execution_status,'PUBLISHED');});
test('unknown route cost is preserved in proposed packets',()=>{const r=openRouteScout({formation,directory:{destinations:[{...directory.destinations[1],cost:'UNKNOWN'}]}});assert.equal(prepareRouteAssets({formation,candidates:r.candidates})[0].cost_state,'UNKNOWN');});
