import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {FileStore} from '../../runtime/store.js';
import {StreamlinedMarketingEngineV2,V2_GRAPH,existingEditorialTransport,existingXTransport} from '../../runtime/streamlined-engine-v2.js';
import {editorialOutreachAdapter} from '../../runtime/adapters.js';

const scan={publication_state:'PUBLISHED',source_revision:'scan-2026-10-10:a1',formation:{id:'india-semiconductor-buildout',state:'FORMING',causal_chain:['policy','investment','capacity'],evidence:[{id:'e1',url:'https://example.test/source',claim:'Verified investment milestone'}],uncertainty:['Delivered capacity remains unconfirmed.'],strengthening_evidence:['A named facility reached a milestone.'],weakening_evidence:['Output is not yet verified.'],break_conditions:['Construction stops.'],companies:['Example Co'],tickers:['EXM']}};
const executable={id:'SEMICONDUCTOR-FOR-YOU',editorial_relevance:true,evidence_suitable:true,endpoint:{address:'editor@example.test',verification_state:'VERIFIED'},delivery:{method:'EMAIL',supported:true},connector:{authorized:true},finished_contribution_supported:true};
const unsupported={id:'RELEVANT-NO-ROUTE',editorial_relevance:true,evidence_suitable:true,endpoint:{address:null,verification_state:'UNKNOWN'},delivery:{method:'FORM',supported:false},connector:{authorized:false},finished_contribution_supported:true};
const assetBuilder=async({scan,route})=>({subject:"Contribution idea: India’s semiconductor ecosystem beyond the fab",body:`Hi Editor,\n\nI’m Sean Walker, working on EMRADAR. ${scan.formation.evidence[0].claim}. The formation is ${scan.formation.state}. ${scan.formation.uncertainty[0]} Would this evidence-backed contribution be useful for ${route.id}?\n\nRegards,\nSean Walker\nEMRADAR`,to:route.endpoint.address,delivery_method:route.delivery.method,evidence_summary:'Evidence-backed build-out with explicit capacity uncertainty.',required_visual_or_attachment:'NONE'});
async function fixture({destinations=[executable,unsupported],send}={}){const dir=await mkdtemp(path.join(os.tmpdir(),'emradar-v2-'));const store=new FileStore(dir);let calls=0;const transport={quote:async()=>({currency:'AUD',max_cost_aud:0}),send:send|| (async x=>{calls++;return {id:'provider-1',status:'ACCEPTED',receipt:{message_id:'provider-1',idempotency_key:x.idempotency_key},actual_cost_aud:0};})};const engine=new StreamlinedMarketingEngineV2({store,destinations,transports:{EMAIL:transport},assetBuilder});return {engine,store,calls:()=>calls};}

test('complete graph prepares relevant review assets and separates transport capability',async()=>{const f=await fixture();const r=await f.engine.prepare({campaign_id:'V2_TEST',scan});assert.deepEqual(V2_GRAPH,['SCAN','MATCH','PREPARE','VERIFY','OWNER_REVIEW','DISTRIBUTE','RECORD','LEARN']);assert.equal(r.proposals.length,2);assert.equal(r.opportunities.length,1);assert.equal(r.external_actions,0);const records=await Promise.all(r.proposals.map(p=>f.store.get('v2:review:'+p.proposal_id))),p=records.find(p=>p.destination===executable.id),reviewOnly=records.find(p=>p.destination===unsupported.id);assert.deepEqual(p.binding.evidence.causal_chain,scan.formation.causal_chain);assert.deepEqual(p.binding.evidence.strengthening_evidence,scan.formation.strengthening_evidence);assert.equal(p.asset.subject,"Contribution idea: India’s semiconductor ecosystem beyond the fab");assert.equal(reviewOnly.delivery_capability,'UNAVAILABLE_REVIEW_ONLY');});
test('reject creates no distribution work and decision is immutable',async()=>{const f=await fixture();const r=await f.engine.prepare({campaign_id:'V2_REJECT',scan});const p=r.proposals[0];await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'REJECT'});assert.equal(await f.store.get('v2:work:'+p.proposal_id),null);await assert.rejects(()=>f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'}),/OWNER_DECISION_IMMUTABLE/);});
test('exact approval queues, sends exact asset, persists provider receipt and prevents duplicate',async()=>{let delivered;const f=await fixture({send:async x=>{delivered=x;return {id:'mail-1',status:'ACCEPTED',receipt:{accepted:['editor@example.test']},actual_cost_aud:0};}});const r=await f.engine.prepare({campaign_id:'V2_SEND',scan}),p=r.proposals[0];await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});const [first]=await f.engine.distribute();assert.equal(first.status,'SUBMITTED');assert.deepEqual(delivered.asset,p.asset);const receipt=await f.store.get('v2:receipt:'+first.receipt.id);assert.equal(receipt.provider_receipt.accepted[0],'editor@example.test');await f.store.put('v2:work:'+p.proposal_id,{...(await f.store.get('v2:work:'+p.proposal_id)),status:'QUEUED'});const [second]=await f.engine.distribute();assert.equal(second.duplicate,true);});
test('ambiguous send is never automatically retried',async()=>{let calls=0;const f=await fixture({send:async()=>{calls++;throw new Error('timeout after POST');}});const r=await f.engine.prepare({campaign_id:'V2_AMBIGUOUS',scan}),p=r.proposals[0];await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});assert.equal((await f.engine.distribute())[0].status,'AMBIGUOUS');await f.store.put('v2:work:'+p.proposal_id,{...(await f.store.get('v2:work:'+p.proposal_id)),status:'QUEUED'});assert.equal((await f.engine.distribute())[0].duplicate,true);assert.equal(calls,1);});
test('destination failures are isolated and restart-safe queued work resumes',async()=>{const second={...executable,id:'SECOND',endpoint:{...executable.endpoint,address:'two@example.test'}};const f=await fixture({destinations:[executable,second],send:async({asset})=>{if(asset.to==='editor@example.test'){const e=new Error('rejected before send');e.definitely_unsent=true;throw e;}return {id:'mail-2',status:'ACCEPTED',receipt:{accepted:[asset.to]},actual_cost_aud:0};}});const r=await f.engine.prepare({campaign_id:'V2_ISOLATION',scan});for(const p of r.proposals)await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});const results=await f.engine.distribute();assert.deepEqual(results.map(x=>x.status).sort(),['FAILED','SUBMITTED']);});
test('historical V1 receipt identifier prevents redelivery',async()=>{const f=await fixture();const r=await f.engine.prepare({campaign_id:'V2_HISTORY',scan}),p=r.proposals[0],saved=await f.store.get('v2:review:'+p.proposal_id);await f.store.put('receipt:'+saved.delivery_key,{id:saved.delivery_key,execution_status:'SUBMITTED',provider_receipt:{legacy:true}});await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});const [result]=await f.engine.distribute();assert.equal(result.duplicate,true);assert.equal(f.calls(),0);});
test('feedback records reply re-entry and requires proof before PUBLISHED',async()=>{const f=await fixture();const r=await f.engine.prepare({campaign_id:'V2_FEEDBACK',scan}),p=r.proposals[0];await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});const [{receipt}]=await f.engine.distribute();const learned=await f.engine.learn({receipt_id:receipt.id,events:[{type:'EDITORIAL_REPLY',payload:{request:'article'}},{type:'PUBLICATION_CONFIRMED',url:'https://example.test/published'}]});assert.equal(learned.receipt.execution_status,'PUBLISHED');assert.equal(learned.reentry_events,1);assert.ok((await f.store.keys('v2:preparation-work:')).length===1);});
test('unknown spend requires owner authority and no transport call',async()=>{let calls=0;const f=await fixture();f.engine.transports.EMAIL={quote:async()=>({currency:'AUD',max_cost_aud:'UNKNOWN'}),send:async()=>{calls++;}};const r=await f.engine.prepare({campaign_id:'V2_COST',scan}),p=r.proposals[0];await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});const [result]=await f.engine.distribute();assert.equal(result.error,'OWNER_AUTHORIZATION_REQUIRED_UNKNOWN_SPEND');assert.equal(calls,0);});
test('existing approved editorial adapter contract is compatible',async()=>{let delivered;const adapter=editorialOutreachAdapter({routeSupported:()=>true,sendEmail:async input=>{delivered=input;return {id:'relay-1',status:'ACCEPTED',receipt:{provider:'existing-relay'}};}});const asset={subject:'Subject',body:'Body',to:'editor@example.test',delivery_method:'EMAIL',copy:'Subject: Subject\n\nBody',email:{to:'editor@example.test'},delivery:{destination_id:'SFY',access_method:'verified email',evidence_source_url:'https://example.test/contact',public_contact_point:'editor@example.test',verification_state:'VERIFIED'}};const transport=existingEditorialTransport(adapter);const result=await transport.send({asset,idempotency_key:'stable-key',approval:{proposal_id:'p1',review_hash:'h1'}});assert.equal(result.status,'ACCEPTED');assert.equal(result.receipt.provider,'existing-relay');assert.equal(delivered.asset,asset);assert.equal(delivered.idempotency_key,'stable-key');assert.equal(delivered.approvalBinding.proposal.asset,asset);});
test('existing authenticated X adapter preserves post identifier and receipt without inventing spend',async()=>{let delivered;const adapter={authorized:async()=>true,publish:async(asset,key,product)=>{delivered={asset,key,product};return {id:'post-1',status:'PUBLISHED',url:'https://x.com/i/web/status/post-1'};},collect:async()=>({status:'AVAILABLE',events:[]})};const transport=existingXTransport(adapter);assert.deepEqual(await transport.quote(),{currency:'AUD',max_cost_aud:'UNKNOWN'});const result=await transport.send({asset:{copy:'reviewed',format:'image'},idempotency_key:'stable-x'});assert.equal(result.id,'post-1');assert.equal(result.receipt.url,'https://x.com/i/web/status/post-1');assert.deepEqual(delivered,{asset:{copy:'reviewed',format:'image'},key:'stable-x',product:'EMRADAR'});});
test('transport outcome collection feeds the existing learning loop',async()=>{const f=await fixture();const r=await f.engine.prepare({campaign_id:'V2_COLLECT',scan}),p=r.proposals[0];await f.engine.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'});const [{receipt}]=await f.engine.distribute();f.engine.transports.EMAIL.collect=async()=>({status:'AVAILABLE',source:'provider',events:[{type:'EDITORIAL_REPLY',payload:{request:'article'}}]});const learned=await f.engine.collect(receipt.id);assert.equal(learned.reentry_events,1);assert.equal((await f.store.get('v2:feedback-work:'+receipt.id)).status,'OBSERVED');});
test('intake rejects unpublished scans and recommendation language',async()=>{const f=await fixture();await assert.rejects(()=>f.engine.prepare({campaign_id:'BAD1',scan:{...scan,publication_state:'DRAFT'}}),/PUBLISHED_SCAN_REQUIRED/);await assert.rejects(()=>f.engine.prepare({campaign_id:'BAD2',scan:{...scan,formation:{...scan.formation,recommendation:'BUY'}}}),/INVESTMENT_RECOMMENDATION_FORBIDDEN/);});
