import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {FileStore} from '../../runtime/store.js';
import {autonomousV2ScanCycle,recoverV2ReviewCoverage} from '../../runtime/v2-autonomous-source.js';

const scan={snapshot_date:'2026-10-10',publication_state:'PUBLISHED',records:[{id:'october-ten-primary',theme:'October 10 formation',status:'FORMING',location:'Chile',causal_chain:{world_change:['A verified change occurred.'],industries:['Copper mining']},evidence:[{fact:'A source reported a verified milestone.',url:'https://example.test/source'}],contradictions:['Output is not yet realised.'],chain_evolution:{strengthening_evidence:['A milestone was reported.'],weakening_evidence:[],break_conditions:['The project is cancelled.'],unresolved_evidence:['Delivery remains unverified.']},listed_players:[]}]};
const bytes=Buffer.from(JSON.stringify(scan)),source_sha256=crypto.createHash('sha256').update(bytes).digest('hex');
const attestation={product:'EMRADAR',snapshot_date:scan.snapshot_date,source_path:'data/checkpoints/discovery-2026-10-10.json',source_sha256,publication_state:'PUBLISHED',downstream_release_allowed:true,native_gates:{evidence:'PASS',editorial:'PASS',brand:'PASS',risk:'PASS',publication:'PASS'},campaign_authority:{campaign_id:'EMRADAR_2026_10_10_LAUNCH',required_stop:'PUBLICATION_REVIEW',external_publication_allowed:false}};
const fetcher=(current=attestation,currentScan=scan)=>async url=>({ok:true,arrayBuffer:async()=>Buffer.from(JSON.stringify(url.includes('/verification/')?current:currentScan))});
async function fixture(){const store=new FileStore(await mkdtemp(path.join(os.tmpdir(),'v2-auto-')));let calls=0;const runtime={prepare:async({campaign_id,scan})=>{calls++;const record={campaign_id,source_revision:scan.source_revision,status:'AWAITING_OWNER_REVIEW',proposals:[],external_actions:0};await store.put('v2:campaign:'+campaign_id,record);return record;}};return {store,runtime,calls:()=>calls};}

test('published attested scan is admitted and prepared once with no distribution',async()=>{const f=await fixture(),first=await autonomousV2ScanCycle({store:f.store,runtime:f.runtime,fetcher:fetcher(),log:()=>{}}),second=await autonomousV2ScanCycle({store:f.store,runtime:f.runtime,fetcher:fetcher(),log:()=>{}});assert.equal(first.status,'PREPARED');assert.equal(first.scan_date,'2026-10-10');assert.equal(first.source_sha256,source_sha256);assert.equal(first.external_actions,0);assert.equal(second.duplicate,true);assert.equal(f.calls(),1);assert.ok(await f.store.get('v2:review_package:EMRADAR_2026_10_10_LAUNCH'));});
test('bounded coverage recovery reuses the attested intake and persists expanded review once',async()=>{const f=await fixture();await autonomousV2ScanCycle({store:f.store,runtime:f.runtime,fetcher:fetcher(),log:()=>{}});let calls=0;f.runtime.prepare=async input=>{calls++;assert.equal(input.expand_review,true);const record={campaign_id:input.campaign_id,status:'AWAITING_OWNER_REVIEW',proposals:[{proposal_id:'new'}],route_dispositions:[{destination:'NEW'}],external_actions:0};await f.store.put('v2:campaign:'+input.campaign_id,record);return record;};const result=await recoverV2ReviewCoverage({store:f.store,runtime:f.runtime,campaign_id:'EMRADAR_2026_10_10_LAUNCH',fetcher:fetcher(),log:()=>{}}),duplicate=await recoverV2ReviewCoverage({store:f.store,runtime:f.runtime,campaign_id:'EMRADAR_2026_10_10_LAUNCH',fetcher:()=>{throw new Error('SHOULD_NOT_FETCH');},log:()=>{}});assert.equal(calls,1);assert.equal(result.proposal_count,1);assert.equal(duplicate.duplicate,true);assert.equal((await f.store.get('v2:review_package:EMRADAR_2026_10_10_LAUNCH')).proposals[0].proposal_id,'new');assert.equal((await f.store.get('v2:intake:EMRADAR_2026_10_10_LAUNCH')).proposal_count,1);});
test('all published findings are passed to V2 preparation',async()=>{const second={...scan.records[0],id:'october-ten-second',status:'INVESTIGATE'},multi={...scan,records:[...scan.records,second]},multiBytes=Buffer.from(JSON.stringify(multi)),multiHash=crypto.createHash('sha256').update(multiBytes).digest('hex'),multiAttestation={...attestation,source_sha256:multiHash};const f=await fixture();let count=0;f.runtime.prepare=async({campaign_id,scan})=>{count=scan.formations.length;const record={campaign_id,status:'AWAITING_OWNER_REVIEW',proposals:[],external_actions:0};await f.store.put('v2:campaign:'+campaign_id,record);return record;};await autonomousV2ScanCycle({store:f.store,runtime:f.runtime,fetcher:fetcher(multiAttestation,multi),log:()=>{}});assert.equal(count,2);});
test('unpublished scan is rejected before persistence',async()=>{const f=await fixture();await assert.rejects(()=>autonomousV2ScanCycle({store:f.store,runtime:f.runtime,fetcher:fetcher({...attestation,publication_state:'DRAFT'},{...scan,publication_state:'DRAFT'}),log:()=>{}}),/NOT_PUBLISHED/);assert.equal(await f.store.get('v2:intake:EMRADAR_2026_10_10_LAUNCH'),null);});
test('invalid attestation is rejected before persistence',async()=>{const f=await fixture();await assert.rejects(()=>autonomousV2ScanCycle({store:f.store,runtime:f.runtime,fetcher:fetcher({...attestation,source_sha256:'bad'}),log:()=>{}}),/ATTESTATION_MISMATCH/);assert.equal((await f.store.keys('v2:intake:')).length,0);});
test('interrupted preparation resumes from admitted receipt',async()=>{const f=await fixture();let first=true;const runtime={prepare:async input=>{if(first){first=false;throw new Error('INTERRUPTED');}return f.runtime.prepare(input);}};await assert.rejects(()=>autonomousV2ScanCycle({store:f.store,runtime,fetcher:fetcher(),log:()=>{}}),/INTERRUPTED/);assert.equal((await f.store.get('v2:intake:EMRADAR_2026_10_10_LAUNCH')).status,'ADMITTED');const resumed=await autonomousV2ScanCycle({store:f.store,runtime,fetcher:fetcher(),log:()=>{}});assert.equal(resumed.status,'PREPARED');assert.equal(resumed.external_actions,0);});
test('server keeps V1 inactive while the existing scheduled route invokes V2 intake',async()=>{const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../../server.js',import.meta.url),'utf8'));assert.doesNotMatch(source,/\['\/PRODUCT_INPUT','\/SCHEDULED_CYCLE'/);assert.match(source,/autonomousV2ScanCycle\(\{store:s,runtime:await v2Runtime\(\)\}\)/);assert.match(source,/v1_execution:'INACTIVE'/);});
