import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {FileStore} from '../../runtime/store.js';
import {authorizedV2Owner,createV2Runtime} from '../../runtime/v2-integration.js';
import {editorialOutreachAdapter} from '../../runtime/adapters.js';
import {destinations as productionDestinations,assetBuilder as productionAssetBuilder} from '../../runtime/v2-production.js';
import fs from 'node:fs/promises';

const scan={publication_state:'PUBLISHED',source_revision:'published:r1',formation:{id:'sfy-integration',state:'FORMING',causal_chain:['investment','construction','capacity'],evidence:[{id:'e1',url:'https://example.test/evidence',claim:'Verified construction milestone'}],uncertainty:['Delivered capacity remains unconfirmed.'],strengthening_evidence:['Construction advanced.'],weakening_evidence:['Production is not verified.'],break_conditions:['Construction stops.'],companies:[],tickers:[]}};
const destination={id:'SEMICONDUCTOR-FOR-YOU',editorial_relevance:true,evidence_suitable:true,endpoint:{address:'editor@example.test',verification_state:'VERIFIED'},delivery:{method:'EMAIL',supported:true},connector:{authorized:true},finished_contribution_supported:true};
const assetBuilder=async({route})=>({subject:"Contribution idea: India’s semiconductor ecosystem beyond the fab",body:'Hi Editor,\n\nI’m Sean Walker, working on EMRADAR. Verified construction milestone. The formation is FORMING. Delivered capacity remains unconfirmed. Would this evidence-backed contribution be useful?\n\nRegards,\nSean Walker\nEMRADAR',to:route.endpoint.address,delivery_method:'EMAIL',copy:"Subject: Contribution idea: India’s semiconductor ecosystem beyond the fab\n\nBody",email:{to:route.endpoint.address},delivery:{destination_id:route.id,access_method:'verified email',evidence_source_url:'https://example.test/contact',public_contact_point:route.endpoint.address,verification_state:'VERIFIED'},evidence_summary:'Verified milestone with explicit uncertainty.'});
async function setup({send}={}){const directory=await mkdtemp(path.join(os.tmpdir(),'v2-integration-')),store=new FileStore(directory);let calls=0;const adapter=editorialOutreachAdapter({routeSupported:()=>true,sendEmail:send|| (async input=>{calls++;return {id:'provider-1',status:'ACCEPTED',receipt:{idempotency_key:input.idempotency_key}};})});const args={store,integrationModule:{destinations:[destination],assetBuilder},editorialAdapter:adapter};return {store,args,runtime:await createV2Runtime(args),calls:()=>calls};}

test('owner authentication is constant-time compatible and fail closed',()=>{assert.equal(authorizedV2Owner('Bearer exact','exact'),true);assert.equal(authorizedV2Owner('Bearer wrong','exact'),false);assert.equal(authorizedV2Owner('Bearer exact',''),false);});
test('persistent restart resumes approved queued work through existing adapter',async()=>{const f=await setup();const campaign=await f.runtime.prepare({campaign_id:'V2_INTEGRATION',scan}),p=campaign.proposals[0];process.env.MARKETING_PUBLICATION_REVIEW_TOKEN='owner-secret';await assert.rejects(()=>f.runtime.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'},'Bearer wrong'),/OWNER_PUBLICATION_REVIEW_AUTH_REQUIRED/);await f.runtime.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'},'Bearer owner-secret');const restarted=await createV2Runtime(f.args);const [result]=await restarted.distribute();assert.equal(result.status,'SUBMITTED');assert.equal(f.calls(),1);delete process.env.MARKETING_PUBLICATION_REVIEW_TOKEN;});
test('October history is read-only and cross-version receipt suppresses delivery',async()=>{const f=await setup();const history={campaign_id:'EMRADAR_2026_10_07_LAUNCH',decision:'APPROVED',immutable:true};await f.store.put('publication_approval:october-7',history);const campaign=await f.runtime.prepare({campaign_id:'V2_HISTORY_BOUNDARY',scan}),p=campaign.proposals[0],proposal=await f.runtime.review(p.proposal_id);await f.store.put('receipt:'+proposal.delivery_key,{id:proposal.delivery_key,execution_status:'SUBMITTED',provider_receipt:{historical:true}});process.env.MARKETING_PUBLICATION_REVIEW_TOKEN='owner-secret';await f.runtime.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'},'Bearer owner-secret');const [result]=await f.runtime.distribute();assert.equal(result.duplicate,true);assert.equal(f.calls(),0);assert.deepEqual(await f.store.get('publication_approval:october-7'),history);delete process.env.MARKETING_PUBLICATION_REVIEW_TOKEN;});
test('simulated end-to-end graph closes feedback without live delivery',async()=>{const f=await setup();const campaign=await f.runtime.prepare({campaign_id:'V2_END_TO_END',scan}),p=campaign.proposals[0];process.env.MARKETING_PUBLICATION_REVIEW_TOKEN='owner-secret';await f.runtime.decide({proposal_id:p.proposal_id,review_hash:p.review_hash,decision:'APPROVE'},'Bearer owner-secret');const [{receipt}]=await f.runtime.distribute();const feedback=await f.runtime.feedback({receipt_id:receipt.id,events:[{type:'EDITORIAL_REPLY',payload:{request:'article'}}],collection:{status:'SIMULATED'}});assert.equal(feedback.reentry_events,1);assert.equal(feedback.learning.destinations[destination.id].replies,1);assert.equal((await f.store.get('v2:feedback-work:'+receipt.id)).status,'OBSERVED');delete process.env.MARKETING_PUBLICATION_REVIEW_TOKEN;});
test('integration refuses nonpersistent or missing adapter configuration',async()=>{await assert.rejects(()=>createV2Runtime({integrationModule:{destinations:[],assetBuilder}}),/V2_PERSISTENT_STORE_REQUIRED/);const directory=await mkdtemp(path.join(os.tmpdir(),'v2-missing-'));await assert.rejects(()=>createV2Runtime({store:new FileStore(directory),integrationModule:{destinations:[],assetBuilder}}),/V2_APPROVED_EMAIL_ADAPTER_REQUIRED/);});
test('production integration preserves directory routes, branded email, and one consolidated X visual',async()=>{assert.ok(productionDestinations.length>0);const route=productionDestinations.find(r=>r.delivery.method==='EMAIL'),formation={...scan.formation,title:'Verified formation',industries:[...route.industries],geography:[],causal_chain_source:{world_change:['Verified construction milestone']}},productionScan={...scan,snapshot_date:'2026-10-10',formation,formations:Array.from({length:6},(_,i)=>({...formation,id:'formation-'+i,title:'Formation '+i}))};assert.equal(route.editorial_relevance(productionScan,route),true);const asset=await productionAssetBuilder({scan:{...productionScan,formations:undefined},route});assert.equal(asset.email.from.address,'sean@emradar.net');assert.equal(asset.copy,`Subject: ${asset.subject}\n\n${asset.email.body}`);assert.equal(asset.delivery.public_contact_point,asset.to);const x=productionDestinations.find(r=>r.id==='EMRADAR-X-OROKNOWS'),xAsset=await productionAssetBuilder({scan:productionScan,route:x});assert.equal(x.delivery.supported,true);assert.equal(x.connector.authorized,true);assert.equal(xAsset.mime,'image/png');assert.ok(Buffer.from(xAsset.base64,'base64').length>0);assert.equal(xAsset.combined_review_artifact,true);assert.equal(xAsset.consolidated_scan,true);assert.ok(xAsset.copy.length<=280);});
test('server cutover has no V1 timers and hard-disables V1 mutations and V2 distribution',async()=>{const source=await fs.readFile(new URL('../../server.js',import.meta.url),'utf8');assert.doesNotMatch(source,/setInterval\(\(\)=>normalCycle|setInterval\(\(\)=>distributionCycle/);assert.match(source,/V1_EXECUTION_PERMANENTLY_RETIRED/);assert.match(source,/MARKETING_V2_DISTRIBUTION_ENABLED.*EXTERNAL_DISTRIBUTION_DISABLED/);assert.match(source,/EMRADAR_MARKETING_ENGINE_V2/);});
